spring:
  profiles:
    active: dev
---
spring:
  profiles: dev #开发环境
  application:
    name: springboot-eureka-config-dev

---
spring:
  profiles: test  #测试环境
  application:
    name: springboot-eureka-config-test

---
spring:
  profiles: prod  #生成环境
  application:
    name: springboot-eureka-config-prod
